<?php
$categoryCollection = Mage::getModel("catalog/category")->getCollection();

?>
<div class="box">
    <div class="container-list">
        <div class="add">
            <div class="title">Category Information</div>
            <a href='<?php echo $this->getUrl('admin/catalog_category/form') ?>'><button class="add_btn">Add</button></a>
        </div>
        <table>
                        <tr>
                            <!-- <th width='200vh'>Category ID</th> -->
                            <th width='200vh'>Category Name</th>
                            <th width='200vh'>Status</th>
                            <th width='200vh'>Edit</th>
                            <th width='200vh'>Delete</th>
                        </tr>

<?php
foreach ($categoryCollection->getData() as $category) {
    echo "<tr><td class = 'column'>" . $category->getCategoryName() . "</td><td class = 'column'>" . $category->getStatus(). "</td>";
    ?>
    <td align='center' class='button'> <a
                        href='<?php echo $this->getUrl('admin/catalog_category/form/') ?>?id=<?php echo $category->getCategoryId() ?>'><button
                            class='upd'>Edit</button></a> </td>
                <td align='center' class='button'> <a
                        href='<?php echo $this->getUrl('admin/catalog_category/delete/') ?>?id=<?php echo $category->getCategoryId() ?>'><button
                            class='del'>Delete</button></a> </td>
                </tr>
    <?php
}
?>
</table>
</div>
</div>