<?php
$data = $this->getBrand(); 
//print_r($data);
//var_dump($data->getBrandName()); 
?>
<div class="box">


    <div class="form" style="border:1px solid black; width:30vw; padding: 15px">
        <h2>Brand Form </h2><br>
        <form method="POST" action="<?php echo $this->getUrl('brand/brand/save'); ?>">
        <input type="hidden" name="brand[brand_id]" value="<?php echo $data->getBrandId()?>">
            <div class="row">
                <label for="name">Name : </label>
                <input type="text" name="brand[brand_name]" value="<?php echo $data->getBrandName()?>">
            </div>
            <div class="row">
                <label for="name">status </label>
                <select id="status" name="brand[status]" class="row" required>
                    <option value="">---select---</option>
                    <option value="1" <?php echo (($data->getStatus() == "Enabled") ? 'selected' : '') ?>>Enabled</option>
                    <option value="0" <?php echo (($data->getStatus() == "Disabled") ? 'selected' : '') ?>>Disabled</option>
                </select>
            </div>
            <div class="row" id="sbtButton">
                <input name="submit[submit]" type="submit" value="Submit">
            </div>
        </form>
    </div>

</div>