


<header class="header-fixed" style=" margin-left:0%; padding-left:0%;">

	<div class="header-limiter" style=" margin-left:0%; padding-left:0%;" >

		<h1><a href="#" style="font-size:3vw;">Company<span>logo</span></a></h1>

		<nav style="font-size:1.5vw">
			<a href="#">Home</a>
			<a href="#">Blog</a>
			<a href="#">Pricing</a>
			<a href="#">About</a>
			<a href="#">Faq</a>
			<a href="#">Contact</a>
		</nav>

	</div>

</header>

<!-- You need this element to prevent the content of the page from jumping up -->
<!-- <div class="header-fixed-placeholder"></div> -->

<!-- The content of your page would go here. -->



<!-- 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>

	$(document).ready(function(){

		var showHeaderAt = 150;

		var win = $(window),
				body = $('body');

		// Show the fixed header only on larger screen devices

		if(win.width() > 400){

			// When we scroll more than 150px down, we set the
			// "fixed" class on the body element.

			win.on('scroll', function(e){

				if(win.scrollTop() > showHeaderAt) {
					body.addClass('fixed');
				}
				else {
					body.removeClass('fixed');
				}
			});

		}

	});

</script> -->


<!-- Demo ads. Please ignore and remove. -->

