<?php
$productModel = $this->getProduct(); ?>
<div class="box">

    <div class="form" style="border:1px solid black; width:30vw; padding: 15px">
        <h2>Product Form</h2>

        <form method="POST" action="<?php echo $this->getUrl("admin/catalog_product/save");
        ?>">
            <div class="row">
                <input type="hidden" name="catalog_product[product_id]"
                    value="<?php echo $productModel->getProductId() ?>">
            </div>
            <div class="row">
                <label for="sku">SKU</label>
                <input type="text" name="catalog_product[sku]" id="sku" value="<?php echo $productModel->getSku() ?>">
            </div>
            <div class="row">
                <label for="name">Name</label>
                <input type="text" name="catalog_product[name]" id="name"
                    value="<?php echo $productModel->getName() ?>">
            </div>

            <div class="row">
                <label for="color">Color </label>
                <input type="text" name="catalog_product[color]" id="color"
                    value="<?php echo $productModel->getColor() ?>">
            </div>

            <div class="row">
                <label for="size">Size  </label>
                <input type="text" name="catalog_product[size]" id="size"
                    value="<?php echo $productModel->getSize() ?>">
            </div>

            <div class="row">
                <label for="description">Description 
                    <textarea name="catalog_product[description]" id="description" cols="40"
                        rows="10"> <?php echo $productModel->getDescription() ?></textarea>
                </label>
            </div>

            <div class="row">
                <label for="image_link">Image Link </label>
                <input type="file" name="catalog_product[image_link]" id="image_link"
                    value="<?php echo $productModel->getImageLink() ?>">
            </div>

            <div class="row">
                <label for="link">Link  </label>
                <input type="file" name="catalog_product[link]" id="link"
                    value="<?php echo $productModel->getLink() ?>">
            </div>

            <div class="row">
                <label for="category_id">Category ID  </label>
                <input type="number" name="catalog_product[category_id]" id="category_id"
                    value="<?php echo $productModel->getCategoryId() ?>">
            </div>

            <div class="row">
                <label for="price">Price  </label>
                <input type="number" name="catalog_product[price]" id="price"
                    value="<?php echo $productModel->getPrice() ?>">
            </div>

            <div class="row">
                <label for="mfr_cost">MFR Cost</label>
                <input type="number" name="catalog_product[mfr_cost]" id="mfr_cost"
                    value="<?php echo $productModel->getMfrCost() ?>">
            </div>

            <div class="row">
                <label for="shipping_cost">Shipping Cost</label>
                <input type="number" name="catalog_product[shipping_cost]" id="shipping_cost"
                    value="<?php echo $productModel->getShippingCost() ?>">
            </div>

            <div class="row">
                <label for="total_cost">Total Cost</label>
                <input type="number" name="catalog_product[total_cost]" id="total_cost"
                    value="<?php echo $productModel->getTotalCost() ?>">
            </div>

            <div class="row">
                <label for="margin_percentage">Margin Percentage </label>
                <input type="number" name="catalog_product[margin_percentage]" id="margin_percentage"
                    value="<?php echo $productModel->getMarginPercentage() ?>">
            </div>

            <div class="row">
                <label for="min_price">Min Price </label>
                <input type="number" name="catalog_product[min_price]" id="min_price"
                    value="<?php echo $productModel->getMinPrice() ?>">
            </div>

            <div class="row">
                <label for="status">Status  </label>
                <select id="status" name="catalog_product[status]" required>
                    <option value="">---select---</option>
                    <option value="1" <?php echo $productModel->getStatus() == "1" ? "Selected" : "" ?>>Enabled</option>
                    <option value="0" <?php echo $productModel->getStatus() == "0" ? "Selected" : "" ?>>Disabled</option>
                </select>
            </div>

            <div class="row" id="sbtButton">
                <input name="submit[submit]" type="submit" value="Submit">
            </div>
        </form>
    </div>
</div>